defaults: &defaults
  docker:
    - image: typelead/eta:latest

version: 2.0
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          key: eta-hackage-v1200-etlas-cache-

      - run: etlas update
      - run: etlas run

      - save_cache:
          key: eta-hackage-v1200-etlas-cache-{{ epoch }}
          paths:
            - "~/.etlas/config"
            - "~/.etlas/packages"
            - "~/.etlas/tools"

workflows:
  version: 2
  full_cycle:
    jobs:
      - build
